title: "Kurvesh Patel"
email: kuru.learning@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Final Year Computer Science Student. Knows Little programming. 
  Not a fan of Machine Learning(as of now).
  Summer Intern '20 at Amazon.
baseurl: "/" 
url: "https://totallynotkurvesh.github.io/" 
twitter_username: kurupatel_
github_username:  totallynotkurvesh

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
